CREATE TABLE Users(
    id BIGINT NOT NULL AUTO_INCREMENT,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'STUDENT',
    password VARCHAR(20) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT UC_Email UNIQUE (email)
);

ALTER TABLE Users ADD CONSTRAINT CK_User_Role
CHECK (role IN ('STUDENT', 'INSTRUCTOR'));