CREATE TABLE Course (
    id BIGINT NOT NULL AUTO_INCREMENT,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title VARCHAR(50) NOT NULL,
    description VARCHAR(255) NOT NULL,
    instructor_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'BUILDING',
    publishedAt TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK_Author FOREIGN KEY (instructor_id) REFERENCES Users(id) ON DELETE CASCADE
);

ALTER TABLE Course ADD CONSTRAINT CK_Course_Status
CHECK (status IN ('BUILDING', 'PUBLISHED'));